### ISSUE TITLE
ModuleNotFoundError: No module named 'search_setup'

### ISSUE THREAD

**Issue by fxmeister** [DuckBoss/ScannyMcScanFace-Python3#3]
**Describe the bug**
Cannot run the example code, missing module "search_setup"

**To Reproduce**
1. Cloned most recent version of the source code.
2. Imported into PyCharm
3. Ran code, got the error ModuleNotFoundError: No module named 'search_setup'

**Expected behavior**
Be able to find all modules in latest version of all referenced libraries, such as praw.

**Desktop (please complete the following information):**
 - Python 3.6
 - OS: macOS High Sierra 10.13.4

**Comment by DuckBoss** [comment]
I'm working on a fix!

**Comment by DuckBoss** [comment]
I fixed the problem! It seems that I accidentally forgot to include the search_setup python script into the repository. Thanks for bringing this to my attention. 
**Here is a link to the latest hotfix release:**
https://github.com/DuckBoss/RedditMediaScanner-Python3/releases/latest
